### ISSUE TITLE
CloseStream Missing

### ISSUE THREAD

**Issue by cchanavat** [gap-packages/loops#12]
I think I may have encountered a small bug here https://github.com/gap-packages/loops/blob/master/gap/quasigroups.gi line 263. The `input := InputTextFile( filename );` stream is never closed and for instance if one tries to call `LoopFromFile` too many times, the number of open stream does not decrease and GAP fails to open new ones and throw errors. [From the doc](https://www.gap-system.org/Manuals/doc/ref/chap10.html):

> Whereas it is cheap to append to a stream, streams do consume system resources, and only a limited number can be open at any time, therefore it is necessary to close a stream as soon as possible using CloseStream (10.2-1).

Adding `CloseStream(input);` a few lines after seems to have fixed the problem.

Here is some minimal example that reproduce the bug (on my computer, it fails after 250 iterations):
```
for i in [0..999] do
     Q := LoopFromFile("/path/to/some/loop/multable.table", " ");
     Print(String(i)); Print("\n");
od;
```

**Comment by nagygp** [comment]
@mchana Thank you very much!
