### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/loops#15]
The last one was 2018, and since then there was a bug fix and the licensing situation was clarified (which is important for people who package GAP and its packages for Linux distributions).

So a new release would be great!

I'd be happy to make that release for you, it's less than 5 minutes of work for me.

**Comment by fingolfin** [comment]
@nagygp would you be willing to make a new release of the `loops` package, or alternatively, give us permission to make one for you?

**Comment by nagygp** [comment]
@fingolfin Sorry for the delay. I will make the new release this evening.

**Comment by fingolfin** [comment]
Thanks!
